all:
	gecko build -defsym "BUILD_NTSC_100=1" -c build_100.json
	gecko build -defsym "BUILD_NTSC_102=1" -c build_102.json
	gecko build -defsym "BUILD_NTSC_102=1" -c build_102_gct.json
clean:
	rm -v code_ntsc100.txt code_ntsc102.txt code_ntsc102.bin
